/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/vps/localize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 카메라 이미지 기반 위치추정
     * @description 사용자 촬영 이미지와 위치추정 메타데이터를 받아 AI 위치추정 결과 또는 fallback 응답을 반환한다.
     */
    post: operations['localize'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/user-sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['createUserSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/routes/indoor': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['createRoute'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/routes/indoor/options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['getRouteOptions'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/facilities/{facilityId}/arrival-check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['checkArrival'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/external-maps/directions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 카카오맵 길찾기 URL 생성
     * @description 현재 위치와 목적지 정보를 받아 카카오맵 앱 딥링크와 웹 길찾기 URL을 생성한다. 인증이 필요 없는 공개 API다.
     */
    post: operations['createDirection'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/destinations/nearest-exit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['findNearestExit'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['createConsultation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationSessionId}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['rejectConsultation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationSessionId}/end': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['endConsultation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationSessionId}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['acceptConsultation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationRequestId}/fallback-events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * WebRTC fallback 이벤트 발행
     * @description WebRTC 상담 중 영상 연결 실패, 음성 상담 전환, 채팅 상담 전환 같은 fallback 상태를 서버에 알린다. 인증이 필요 없는 공개 API다.
     */
    post: operations['publishFallbackEvent'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationRequestId}/data-channel-events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * DataChannel fallback 이벤트 발행
     * @description DataChannel 연결 실패 또는 보조 전달이 필요한 경우 화살표, 안내 메시지, 목적지 변경 이벤트를 서버에 알린다. 인증이 필요 없는 공개 API다.
     */
    post: operations['publishDataChannelEvent'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationId}/transcript': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 상담 전문 저장 */
    post: operations['submitTranscript'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationId}/rating': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['rate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['signup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/stations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getStations'];
    put?: never;
    post: operations['createStation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/stations/{stationId}/floors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getFloors'];
    put?: never;
    post: operations['createFloor'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/route-nodes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getNodes'];
    put?: never;
    post: operations['createNode'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/route-edges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getEdges'];
    put?: never;
    post: operations['createEdge'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/place-exit-recommendations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getRecommendations'];
    put?: never;
    post: operations['createRecommendation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/nearby-places': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getPlaces'];
    put?: never;
    post: operations['createPlace'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/floors/{floorId}/maps': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getMaps'];
    put?: never;
    post: operations['uploadMap'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/facilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getFacilities'];
    put?: never;
    post: operations['createFacility'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/user-sessions/{userSessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserSession'];
    put?: never;
    post?: never;
    delete: operations['deleteUserSession'];
    options?: never;
    head?: never;
    patch: operations['updateUserSession'];
    trace?: never;
  };
  '/api/counselors/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateMe'];
    trace?: never;
  };
  '/api/admin/stations/{stationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getStation'];
    put?: never;
    post?: never;
    delete: operations['deleteStation'];
    options?: never;
    head?: never;
    patch: operations['updateStation'];
    trace?: never;
  };
  '/api/admin/route-nodes/{nodeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getNode'];
    put?: never;
    post?: never;
    delete: operations['deleteNode'];
    options?: never;
    head?: never;
    patch: operations['updateNode'];
    trace?: never;
  };
  '/api/admin/route-edges/{edgeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getEdge'];
    put?: never;
    post?: never;
    delete: operations['deleteEdge'];
    options?: never;
    head?: never;
    patch: operations['updateEdge'];
    trace?: never;
  };
  '/api/admin/nearby-places/{placeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getPlace'];
    put?: never;
    post?: never;
    delete: operations['deletePlace'];
    options?: never;
    head?: never;
    patch: operations['updatePlace'];
    trace?: never;
  };
  '/api/admin/floors/{floorId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['deleteFloor'];
    options?: never;
    head?: never;
    patch: operations['updateFloor'];
    trace?: never;
  };
  '/api/admin/facilities/{facilityId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getFacility'];
    put?: never;
    post?: never;
    delete: operations['deleteFacility'];
    options?: never;
    head?: never;
    patch: operations['updateFacility'];
    trace?: never;
  };
  '/api/admin/counselors/{accountId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get'];
    put?: never;
    post?: never;
    delete: operations['deactivate'];
    options?: never;
    head?: never;
    patch: operations['update'];
    trace?: never;
  };
  '/api/webrtc/ice-servers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** WebRTC ICE 서버 설정 조회 */
    get: operations['getIceServers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations/{stationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getStation_1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations/{stationId}/maps': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getStationMaps'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations/{stationId}/facilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getStationFacilities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['searchStations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations/nearby': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getNearbyStations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/places/{placeId}/recommended-exits': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getRecommendedExits'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/facilities/{facilityId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getFacility_1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/destinations/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['search'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/counselors/consultations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getConsultations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/counselors/consultations/{consultationSessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getConsultationDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationSessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getConsultation'];
    put?: never;
    post?: never;
    delete: operations['cancelConsultation'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationRequestId}/waiting-events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 상담 대기 상태 SSE 구독
     * @description 상담 요청 ID 기준으로 상담 대기 상태 변경 이벤트를 SSE로 구독한다.
     */
    get: operations['subscribeWaitingEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consultations/{consultationId}/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 상담 요약 조회 */
    get: operations['getSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/check-login-id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['checkLoginId'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/counselors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/place-exit-recommendations/{recommendationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['deleteRecommendation'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CameraMetadataRequest: {
      /**
       * @description 카메라 모델
       * @example PINHOLE
       */
      model?: string;
      /**
       * Format: int32
       * @description 촬영 이미지 너비(px)
       * @example 1280
       */
      width?: number;
      /**
       * Format: int32
       * @description 촬영 이미지 높이(px)
       * @example 720
       */
      height?: number;
      /**
       * @description 카메라 내부 파라미터
       * @example [
       *       1050.2,
       *       1048.8,
       *       640,
       *       360
       *     ]
       */
      params?: number[];
      /**
       * @description 카메라 내부 파라미터 출처
       * @example DEVICE_PROFILE
       */
      intrinsicsSource?: string;
    };
    LocalizationRequestMetadata: {
      /**
       * @description 비로그인 사용자 세션 ID
       * @example usr_sess_01JABC
       */
      userSessionId: string;
      /**
       * Format: int64
       * @description 역 ID
       * @example 1
       */
      stationId: number;
      /**
       * Format: double
       * @description 단말 방위각
       * @example 126.8
       */
      heading?: number;
      /**
       * Format: date-time
       * @description 촬영 시각
       * @example 2026-07-23T08:10:11.123Z
       */
      capturedAt?: string;
      /** @description 카메라 메타데이터 */
      camera?: components['schemas']['CameraMetadataRequest'];
    };
    ApiResponseLocalizationResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['LocalizationResponse'];
    };
    LocalizationResponse: {
      /**
       * @description 위치추정 요청 추적 ID
       * @example loc_01JABC
       */
      requestId?: string;
      /**
       * @description 위치 인식 결과 상태
       * @example low_confidence
       * @enum {string}
       */
      resultStatus?:
        | 'success'
        | 'low_confidence'
        | 'no_match'
        | 'timeout'
        | 'ai_server_unavailable'
        | 'overloaded'
        | 'invalid_image'
        | 'invalid_intrinsics'
        | 'map_not_ready'
        | 'internal_error';
      /**
       * @description 위치추정에 사용된 AI 맵 버전
       * @example YS-2026-07-23.1
       */
      mapVersion?: string;
      /**
       * @description 확정한 실내 위치. 캐노니컬 미터 좌표이며 지도에 점으로 찍는다.
       *     위치를 확정하지 못했거나 해당 층의 좌표 정합이 없으면 null 이다.
       */
      position?: components['schemas']['LocalizedPositionResponse'];
      /**
       * Format: int64
       * @description 경로 탐색을 시작할 노드 ID. position 에서 가장 가까운 노드이며
       *     POST /api/routes/indoor 의 startNodeId 로 그대로 넣으면 된다.
       *     위치를 확정하지 못하면 null 이다.
       * @example 123
       */
      startNodeId?: number;
      /**
       * @description 경로 시작 노드의 표시 이름. 시설이 붙어 있으면 시설명이다.
       * @example B2-B3 엘리베이터 A
       */
      startNodeLabel?: string;
      fallbackOptions?: (
        | 'retry_capture'
        | 'select_landmark'
        | 'select_on_map'
        | 'request_consultation'
        | 'retry_capture'
        | 'select_landmark'
        | 'select_on_map'
        | 'request_consultation'
      )[];
      /**
       * Format: int32
       * @description AI 위치추정 처리 시간(ms)
       * @example 2310
       */
      processingTimeMs?: number;
    };
    /** @description 위치 인식으로 확정한 실내 위치. 캐노니컬 미터 좌표이며 지도에 그대로 표시한다. */
    LocalizedPositionResponse: {
      /**
       * Format: int64
       * @description 층 ID
       * @example 2
       */
      floorId?: number;
      /**
       * @description 층 코드
       * @example B2
       */
      floorCode: string;
      /**
       * @description 캐노니컬 X (m)
       * @example -0.975
       */
      mapX?: number;
      /**
       * @description 캐노니컬 Y (m)
       * @example 27.717
       */
      mapY?: number;
      /**
       * @description 캐노니컬 Z (m). 해당 층의 기준 높이이며 위치추정으로 얻은 값이 아니다.
       * @example 0
       */
      mapZ?: number;
      /**
       * @description 앵커 시점 단말이 향한 방향. 캐노니컬 수평면 2D 단위벡터다(FE 스펙 8.5).
       *
       *     FE 는 같은 순간의 WebXR 전방(forwardXr)을 스스로 알고 있고, 이 값과의 각도 차가
       *     XR↔지도 회전이다. 그게 있어야 WebXR 이동량을 지도 위 이동으로 바꿀 수 있다.
       *
       *     AI 가 회전을 주지 않거나 카메라가 바닥·천장을 정면으로 볼 때는 null 이다.
       *     방향이 틀려도 오류가 나지 않고 마커만 엉뚱하게 움직이므로, null 이면
       *     WebXR 정렬을 시작하지 않는 편이 안전하다.
       */
      forwardMap?: components['schemas']['PlanarDirectionResponse'];
      /**
       * @description 위치 정확도(m). GPS 정확도 원처럼 쓴다.
       *     해당 층 좌표 정합의 leave-one-out 평균이며 기준점 위에서 잰 in-sample 잔차가 아니다.
       *     현재 값은 B2 0.497 · B3 1.095.
       * @example 0.497
       */
      accuracyM?: number;
    };
    /** @description 캐노니컬 수평면의 2D 단위벡터. 길이 1 로 정규화돼 있다. */
    PlanarDirectionResponse: {
      /**
       * @description 캐노니컬 X 성분
       * @example 0.93
       */
      x?: number;
      /**
       * @description 캐노니컬 Y 성분
       * @example -0.36
       */
      y?: number;
    };
    UserSessionCreateRequest: {
      /** @enum {string} */
      language?: 'ko' | 'en' | 'ja' | 'zh';
    };
    ApiResponseUserSessionCreateResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['UserSessionCreateResponse'];
    };
    UserSessionCreateResponse: {
      userSessionId?: string;
      /** @enum {string} */
      language?: 'ko' | 'en' | 'ja' | 'zh';
      /** Format: date-time */
      expiresAt?: string;
    };
    RouteCreateRequest: {
      /** Format: int64 */
      stationId: number;
      /** Format: int64 */
      startNodeId: number;
      /** Format: int64 */
      targetNodeId: number;
      /** 경유 노드. 최대 10개(백엔드 `@Size(max = 10)`). 생략하면 빈 목록이다. */
      waypointNodeIds?: number[];
      routeType: string;
      /** @enum {string} */
      language?: 'ko' | 'en' | 'ja' | 'zh';
      /**
       * 사용자의 실제 캐노니컬 좌표. 선택이며 **짝으로 있어야** 쓰인다.
       *
       * 있으면 서버가 진입 노드를 목적지까지의 총 거리가 가장 짧은 것으로 다시 고른다.
       * 옵션 조회(`RouteOptionsRequest`)와 같은 값을 보내야 옵션에서 본 거리와 상세 경로가
       * 일치한다. (S15P11A206-337)
       */
      currentMapX?: number;
      currentMapY?: number;
    };
    ApiResponseRouteResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RouteResponse'];
    };
    RoutePathNode: {
      /** Format: int64 */
      nodeId?: number;
      /** Format: int64 */
      floorId?: number;
      mapX?: number;
      mapY?: number;
      mapZ?: number;
    };
    RouteResponse: {
      routeType?: string;
      displayName?: string;
      available?: boolean;
      unavailableReason?: string;
      unavailableMessage?: string;
      /** Format: int64 */
      startNodeId?: number;
      /** Format: int64 */
      targetNodeId?: number;
      totalDistanceM?: number;
      /** Format: int32 */
      estimatedTimeSec?: number;
      steps?: components['schemas']['RouteStep'][];
      pathNodes?: components['schemas']['RoutePathNode'][];
    };
    RouteStep: {
      /** Format: int32 */
      order?: number;
      /** Format: int64 */
      fromNodeId?: number;
      /** Format: int64 */
      toNodeId?: number;
      distanceM?: number;
      /** Format: int32 */
      estimatedTimeSec?: number;
      moveType?: string;
      instruction?: string;
      /**
       * 이전 구간에서 이 구간으로 꺾이는 방향. (S15P11A206-337)
       *
       * **첫 단계이거나 구간이 너무 짧아 판단할 수 없으면 없다** — `straight`와 구분된다.
       * 화면이 지금 쓰는 것은 `instruction` 문장이며, 이 값은 아이콘·다국어에 쓸 여지로 둔다.
       *
       * 카메라 화면의 큰 화살표는 이 값으로 대신할 수 없다. 저것은 **사용자가 지금 보고 있는
       * 쪽을 기준으로** 몇 도 벌어졌는지이고(`routeBearingOf`), 이 값은 앞 구간을 기준으로 한
       * 네 방향이다.
       *
       * @enum {string}
       */
      turn?: 'straight' | 'left' | 'right' | 'around';
      /**
       * 오르내리는 층수. **위로 가면 양수.** 층 이동이 아니거나 층을 알 수 없으면 없다.
       *
       * 같은 층 안의 계단이면 0이다 — 역삼역 B1 개찰구 위 중간층(`floorId`는 B1, `mapZ`가 7.5)이
       * 여기 해당한다.
       *
       * Format: int32
       */
      floorDelta?: number;
    };
    RouteOptionsRequest: {
      /** Format: int64 */
      stationId: number;
      /** Format: int64 */
      startNodeId: number;
      /** Format: int64 */
      targetNodeId: number;
      /** @enum {string} */
      language?: 'ko' | 'en' | 'ja' | 'zh';
      /** 사용자의 실제 캐노니컬 좌표. 선택이며 짝으로 있어야 쓰인다. (S15P11A206-337) */
      currentMapX?: number;
      currentMapY?: number;
    };
    ApiResponseListRouteOptionResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RouteOptionResponse'][];
    };
    RouteOptionResponse: {
      routeType?: string;
      displayName?: string;
      available?: boolean;
      unavailableReason?: string;
      unavailableMessage?: string;
      totalDistanceM?: number;
      /** Format: int32 */
      estimatedTimeSec?: number;
      hasStairsOrEscalator?: boolean;
    };
    ExitArrivalCheckRequest: {
      /**
       * Format: int64
       * @description 현재 층 ID
       * @example 3
       */
      floorId: number;
      /**
       * @description 현재 위치 X (캐노니컬 미터)
       * @example 100.354
       */
      mapX: number;
      /**
       * @description 현재 위치 Y (캐노니컬 미터)
       * @example -39.875
       */
      mapY: number;
    };
    ApiResponseExitArrivalResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ExitArrivalResponse'];
    };
    ExitArrivalResponse: {
      /**
       * Format: int64
       * @description 출구 시설 ID
       * @example 42
       */
      facilityId?: number;
      /**
       * @description 출구 이름(한국어)
       * @example 6번 출구
       */
      nameKo?: string;
      /**
       * @description 출구 이름(영어)
       * @example Exit 6
       */
      nameEn?: string;
      /**
       * Format: int64
       * @description 출구가 속한 층 ID
       * @example 3
       */
      floorId?: number;
      /**
       * @description 도착 여부
       * @example true
       */
      arrived?: boolean;
      /**
       * @description 현재 위치와 출구가 같은 층인지
       * @example true
       */
      sameFloor?: boolean;
      /**
       * @description 출구까지의 평면 거리(m). 층이 다르면 null
       * @example 4.12
       */
      distanceM?: number;
      /**
       * @description 도착으로 판정하는 거리 임계값(m)
       * @example 10
       */
      thresholdM?: number;
    };
    ExternalDestinationRequest: {
      /**
       * Format: int64
       * @description 목적지 장소 ID
       * @example 1
       */
      placeId?: number;
      /**
       * @description 목적지 이름
       * @example 강남역
       */
      name: string;
      /**
       * @description 목적지 위도
       * @example 37.4979
       */
      latitude: number;
      /**
       * @description 목적지 경도
       * @example 127.0276
       */
      longitude: number;
      /**
       * @description 목적지 주소
       * @example 서울특별시 강남구 강남대로 지하396
       */
      address?: string;
    };
    ExternalDirectionRequest: {
      /**
       * @description 외부 지도 제공자. 현재 kakao만 지원한다.
       * @example kakao
       * @enum {string}
       */
      provider: 'kakao';
      /** @description 출발지 좌표 */
      origin: components['schemas']['GeoPointRequest'];
      /** @description 목적지 정보 */
      destination: components['schemas']['ExternalDestinationRequest'];
      /**
       * @description 길찾기 이동 수단. 현재 foot만 지원한다.
       * @example foot
       * @enum {string}
       */
      mode: 'foot';
    };
    GeoPointRequest: {
      /**
       * @description 위도
       * @example 37.5665
       */
      latitude: number;
      /**
       * @description 경도
       * @example 126.978
       */
      longitude: number;
    };
    ExternalDirectionResponse: {
      /**
       * @description 외부 지도 제공자
       * @example kakao
       */
      provider?: string;
      /**
       * @description 카카오맵 앱 딥링크 URL
       * @example kakaomap://route?sp=37.5665,126.9780&ep=37.4979,127.0276&by=foot
       */
      appUrl?: string;
      /**
       * @description 카카오맵 웹 길찾기 URL
       * @example https://map.kakao.com/link/by/walk/현재 위치,37.5665,126.9780/강남역,37.4979,127.0276
       */
      webUrl?: string;
      /**
       * @description 도보 경로 거리(m)
       * @example 2450
       */
      distanceM?: number;
      /**
       * @description 도보 예상 시간(초)
       * @example 2295
       */
      estimatedTimeSec?: number;
    };
    NearestExitRequest: {
      /** Format: int64 */
      stationId: number;
      destinationLatitude: number;
      destinationLongitude: number;
      accessibleOnly?: boolean;
    };
    ApiResponseNearestExitResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['NearestExitResponse'];
    };
    NearestExitResponse: {
      /** Format: int64 */
      exitFacilityId?: number;
      exitNumber?: string;
    };
    ConsultationCreateRequest: {
      userSessionId: string;
      /** Format: int64 */
      stationId: number;
      /** @enum {string} */
      problemType:
        | 'CANNOT_FIND_LOCATION'
        | 'WRONG_DIRECTION'
        | 'CANNOT_FIND_EXIT'
        | 'GATE_PROBLEM'
        | 'ELEVATOR_NEEDED'
        | 'CARD_PROBLEM'
        | 'OTHER';
      /** Format: int64 */
      currentNodeId?: number;
      destinationType?: string;
      /** Format: int64 */
      destinationId?: number;
      videoConsent?: boolean;
      audioConsent?: boolean;
      locationConsent?: boolean;
    };
    ApiResponseConsultationCreateResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationCreateResponse'];
    };
    ConsultationCreateResponse: {
      consultationId?: string;
      /** @enum {string} */
      status?:
        'WAITING' | 'ACCEPTED' | 'IN_PROGRESS' | 'ENDED' | 'CANCELED' | 'REJECTED' | 'FAILED';
      /** Format: date-time */
      requestedAt?: string;
    };
    ApiResponseConsultationRejectResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationRejectResponse'];
    };
    ConsultationRejectResponse: {
      consultationId?: string;
      /** @enum {string} */
      status?:
        'WAITING' | 'ACCEPTED' | 'IN_PROGRESS' | 'ENDED' | 'CANCELED' | 'REJECTED' | 'FAILED';
    };
    ConsultationEndRequest: {
      endedBy: string;
      userSessionId?: string;
    };
    ApiResponseConsultationEndResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationEndResponse'];
    };
    ConsultationEndResponse: {
      consultationId?: string;
      /** @enum {string} */
      status?:
        'WAITING' | 'ACCEPTED' | 'IN_PROGRESS' | 'ENDED' | 'CANCELED' | 'REJECTED' | 'FAILED';
    };
    ApiResponseConsultationAcceptResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationAcceptResponse'];
    };
    ConsultationAcceptResponse: {
      consultationId?: string;
      /** @enum {string} */
      status?:
        'WAITING' | 'ACCEPTED' | 'IN_PROGRESS' | 'ENDED' | 'CANCELED' | 'REJECTED' | 'FAILED';
      /** Format: int64 */
      counselorId?: number;
      signalingRoomId?: string;
      signalingAccessToken?: string;
    };
    ConsultationFallbackEventRequest: {
      /** @enum {string} */
      type:
        | 'VIDEO_FAILED'
        | 'AUDIO_ONLY_REQUESTED'
        | 'AUDIO_FAILED'
        | 'CHAT_ONLY_REQUESTED'
        | 'FALLBACK_CONFIRMED';
      reason?: string;
    };
    ConsultationDataChannelEventRequest: {
      /** @enum {string} */
      type:
        | 'ARROW_POINTED'
        | 'GUIDE_MESSAGE_SENT'
        | 'DESTINATION_CHANGE_REQUESTED'
        | 'DRAW_STROKE_START'
        | 'DRAW_STROKE_MOVE'
        | 'DRAW_STROKE_END'
        | 'DRAW_CLEAR'
        | 'MAP_SYNC'
        | 'CURRENT_LOCATION_CORRECTED';
      payload?: components['schemas']['JsonNode'];
    };
    JsonNode: {
      array?: boolean;
      empty?: boolean;
      null?: boolean;
      float?: boolean;
      number?: boolean;
      container?: boolean;
      string?: boolean;
      /** @enum {string} */
      nodeType?:
        | 'ARRAY'
        | 'BINARY'
        | 'BOOLEAN'
        | 'MISSING'
        | 'NULL'
        | 'NUMBER'
        | 'OBJECT'
        | 'POJO'
        | 'STRING';
      integralNumber?: boolean;
      short?: boolean;
      valueNode?: boolean;
      int?: boolean;
      bigDecimal?: boolean;
      missingNode?: boolean;
      object?: boolean;
      pojo?: boolean;
      double?: boolean;
      bigInteger?: boolean;
      /** @deprecated */
      textual?: boolean;
      boolean?: boolean;
      binary?: boolean;
      long?: boolean;
      floatingPointNumber?: boolean;
      embeddedValue?: boolean;
    };
    ConsultationTranscriptRequest: {
      transcript?: components['schemas']['TranscriptSegmentRequest'][];
      startLocationLabel?: string;
      /** Format: int64 */
      guidedExitFacilityId?: number;
      guidedExitLabel?: string;
      routeType?: string;
    };
    TranscriptSegmentRequest: {
      /** Format: int32 */
      seq: number;
      /** @enum {string} */
      speaker: 'USER' | 'COUNSELOR';
      content: string;
    };
    ApiResponseConsultationSummaryStatusResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationSummaryStatusResponse'];
    };
    ConsultationSummaryStatusResponse: {
      consultationId?: string;
      /** @enum {string} */
      status?: 'PENDING' | 'COMPLETED' | 'FAILED';
    };
    ConsultationRatingRequest: {
      userSessionId: string;
      /** Format: int32 */
      score: number;
    };
    ApiResponseResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['Response'];
    };
    Response: {
      consultationId?: string;
      /** Format: int32 */
      score?: number;
      /** Format: date-time */
      ratedAt?: string;
    };
    SignupRequest: {
      loginId: string;
      password: string;
      name: string;
      /** Format: int64 */
      stationId: number;
    };
    ApiResponseSignupResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['SignupResponse'];
    };
    SignupResponse: {
      /** Format: int64 */
      accountId?: number;
      loginId?: string;
      name?: string;
      /** Format: int64 */
      stationId?: number;
    };
    LoginRequest: {
      loginId: string;
      password: string;
    };
    ApiResponseLoginResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['LoginResponse'];
    };
    LoginResponse: {
      accessToken?: string;
      accountType?: string;
      /** Format: int64 */
      accountId?: number;
      name?: string;
      /** Format: int64 */
      stationId?: number;
      /** @enum {string} */
      status?: 'AVAILABLE' | 'BUSY' | 'OFFLINE';
    };
    StationCreateRequest: {
      nameKo: string;
      nameEn: string;
      lineInfo?: string;
      latitude?: number;
      longitude?: number;
    };
    ApiResponseStationIdResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['StationIdResponse'];
    };
    StationIdResponse: {
      /** Format: int64 */
      stationId?: number;
    };
    FloorCreateRequest: {
      floorCode: string;
      floorName?: string;
      /** Format: int32 */
      floorOrder: number;
      /**
       * @description 층의 캐노니컬 기준 높이(m). 역삼역은 B1=5 · B2=0 · B3=-5.
       *     클라이언트가 층 전환을 ΔY 로 판정하는 데 쓰므로 되도록 넣는다.
       * @example 0
       */
      nominalZ?: number;
    };
    ApiResponseFloorIdResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['FloorIdResponse'];
    };
    FloorIdResponse: {
      /** Format: int64 */
      floorId?: number;
    };
    RouteNodeCreateRequest: {
      /** Format: int64 */
      stationId: number;
      /** Format: int64 */
      floorId: number;
      nodeType: string;
      name?: string;
      mapX: number;
      mapY: number;
      /**
       * @description 캐노니컬 높이(m). 층 바닥이 기준이고 역삼역은 B1=5 · B2=0 · B3=-5.
       *     비워 두면 위치 인식의 노드 스냅이 이 노드를 바닥에 있는 것으로 보므로,
       *     같은 층 안에서 높이가 갈리는 구간(역삼역 B0.5, z=7.5)에서는 되도록 넣는다.
       * @example 0
       */
      mapZ?: number;
      isLandmark?: boolean;
    };
    ApiResponseRouteNodeIdResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RouteNodeIdResponse'];
    };
    RouteNodeIdResponse: {
      /** Format: int64 */
      nodeId?: number;
    };
    RouteEdgeCreateRequest: {
      /** Format: int64 */
      stationId: number;
      /** Format: int64 */
      fromNodeId: number;
      /** Format: int64 */
      toNodeId: number;
      distanceM: number;
      /** Format: int32 */
      estimatedTimeSec?: number;
      moveType: string;
      isAccessible?: boolean;
      isBidirectional?: boolean;
    };
    ApiResponseRouteEdgeIdResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RouteEdgeIdResponse'];
    };
    RouteEdgeIdResponse: {
      /** Format: int64 */
      edgeId?: number;
    };
    PlaceExitRecommendationCreateRequest: {
      /** Format: int64 */
      placeId: number;
      /** Format: int64 */
      exitFacilityId: number;
      /** Format: int32 */
      priority: number;
      reasonKo?: string;
      reasonEn?: string;
      /** Format: int32 */
      walkingTimeMin?: number;
      isPrimary?: boolean;
    };
    ApiResponsePlaceExitRecommendationIdResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['PlaceExitRecommendationIdResponse'];
    };
    PlaceExitRecommendationIdResponse: {
      /** Format: int64 */
      recommendationId?: number;
    };
    NearbyPlaceCreateRequest: {
      /** Format: int64 */
      stationId: number;
      nameKo: string;
      nameEn?: string;
      category: string;
      address?: string;
      latitude?: number;
      longitude?: number;
      externalMapUrl?: string;
    };
    ApiResponseNearbyPlaceIdResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['NearbyPlaceIdResponse'];
    };
    NearbyPlaceIdResponse: {
      /** Format: int64 */
      placeId?: number;
    };
    FloorMapUploadRequest: {
      mapType: string;
      /** Format: int32 */
      width?: number;
      /** Format: int32 */
      height?: number;
      scaleMPerPx?: number;
      originPxX?: number;
      originPxY?: number;
      frameAngleDeg?: number;
    };
    ApiResponseFloorMapIdResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['FloorMapIdResponse'];
    };
    FloorMapIdResponse: {
      /** Format: int64 */
      mapId?: number;
    };
    ExitDetailRequest: {
      exitNumber: string;
      outsideLatitude?: number;
      outsideLongitude?: number;
      descriptionKo?: string;
      descriptionEn?: string;
    };
    FacilityCreateRequest: {
      /** Format: int64 */
      stationId: number;
      /** Format: int64 */
      floorId: number;
      facilityType: string;
      nameKo: string;
      nameEn?: string;
      mapX: number;
      mapY: number;
      /** Format: int64 */
      linkedNodeId?: number;
      isAccessible?: boolean;
      exitDetail?: components['schemas']['ExitDetailRequest'];
    };
    ApiResponseFacilityIdResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['FacilityIdResponse'];
    };
    FacilityIdResponse: {
      /** Format: int64 */
      facilityId?: number;
    };
    UserSessionUpdateRequest: {
      /** @enum {string} */
      language?: 'ko' | 'en' | 'ja' | 'zh';
      /** Format: int64 */
      selectedStationId?: number;
      /** Format: int64 */
      currentNodeId?: number;
      destinationType?: string;
      /** Format: int64 */
      destinationId?: number;
      lastGpsLatitude?: number;
      lastGpsLongitude?: number;
    };
    ApiResponseUserSessionResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['UserSessionResponse'];
    };
    UserSessionResponse: {
      userSessionId?: string;
      /** @enum {string} */
      language?: 'ko' | 'en' | 'ja' | 'zh';
      /** Format: int64 */
      selectedStationId?: number;
      /** Format: int64 */
      currentNodeId?: number;
      destinationType?: string;
      /** Format: int64 */
      destinationId?: number;
      /** Format: date-time */
      expiresAt?: string;
    };
    CounselorSelfUpdateRequest: {
      name?: string;
      currentPassword?: string;
      newPassword?: string;
      /** @enum {string} */
      status?: 'AVAILABLE' | 'BUSY' | 'OFFLINE';
    };
    AccountDetailResponse: {
      /** Format: int64 */
      accountId?: number;
      loginId?: string;
      name?: string;
      /** Format: int64 */
      stationId?: number;
      isActive?: boolean;
      /** @enum {string} */
      status?: 'AVAILABLE' | 'BUSY' | 'OFFLINE';
      /** Format: date-time */
      createdAt?: string;
    };
    ApiResponseAccountDetailResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['AccountDetailResponse'];
    };
    StationUpdateRequest: {
      nameKo: string;
      nameEn: string;
      lineInfo?: string;
      latitude?: number;
      longitude?: number;
    };
    ApiResponseStationDetailResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['StationDetailResponse'];
    };
    FloorResponse: {
      /** Format: int64 */
      floorId?: number;
      floorCode?: string;
      floorName?: string;
      /** Format: int32 */
      floorOrder?: number;
      /**
       * @description 층의 캐노니컬 기준 높이(m). 층 바닥 기준이며 역삼역은 B1=5 · B2=0 · B3=-5.
       *     클라이언트가 층 전환을 판정하는 데 쓴다.
       * @example 0
       */
      nominalZ?: number;
    };
    StationDetailResponse: {
      /** Format: int64 */
      stationId?: number;
      nameKo?: string;
      nameEn?: string;
      lineInfo?: string;
      latitude?: number;
      longitude?: number;
      floors?: components['schemas']['FloorResponse'][];
    };
    RouteNodeUpdateRequest: {
      nodeType: string;
      name?: string;
      mapX: number;
      mapY: number;
      /**
       * @description 캐노니컬 높이(m). 층 바닥이 기준이고 역삼역은 B1=5 · B2=0 · B3=-5.
       *     비워 두면 위치 인식의 노드 스냅이 이 노드를 바닥에 있는 것으로 보므로,
       *     같은 층 안에서 높이가 갈리는 구간(역삼역 B0.5, z=7.5)에서는 되도록 넣는다.
       * @example 0
       */
      mapZ?: number;
      isLandmark?: boolean;
    };
    ApiResponseRouteNodeResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RouteNodeResponse'];
    };
    RouteNodeResponse: {
      /** Format: int64 */
      nodeId?: number;
      /** Format: int64 */
      stationId?: number;
      /** Format: int64 */
      floorId?: number;
      nodeType?: string;
      name?: string;
      mapX?: number;
      mapY?: number;
      /**
       * @description 캐노니컬 높이(m). 층 바닥 기준이며 역삼역은 B1=5 · B2=0 · B3=-5
       * @example 0
       */
      mapZ?: number;
      isLandmark?: boolean;
    };
    RouteEdgeUpdateRequest: {
      distanceM: number;
      /** Format: int32 */
      estimatedTimeSec?: number;
      moveType: string;
      isAccessible?: boolean;
      isBidirectional?: boolean;
    };
    ApiResponseRouteEdgeResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RouteEdgeResponse'];
    };
    RouteEdgeResponse: {
      /** Format: int64 */
      edgeId?: number;
      /** Format: int64 */
      stationId?: number;
      /** Format: int64 */
      fromNodeId?: number;
      /** Format: int64 */
      toNodeId?: number;
      distanceM?: number;
      /** Format: int32 */
      estimatedTimeSec?: number;
      moveType?: string;
      isAccessible?: boolean;
      isBidirectional?: boolean;
    };
    NearbyPlaceUpdateRequest: {
      nameKo: string;
      nameEn?: string;
      category: string;
      address?: string;
      latitude?: number;
      longitude?: number;
      externalMapUrl?: string;
    };
    ApiResponseNearbyPlaceResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['NearbyPlaceResponse'];
    };
    NearbyPlaceResponse: {
      /** Format: int64 */
      placeId?: number;
      /** Format: int64 */
      stationId?: number;
      nameKo?: string;
      nameEn?: string;
      category?: string;
      address?: string;
      latitude?: number;
      longitude?: number;
      externalMapUrl?: string;
      active?: boolean;
    };
    FloorUpdateRequest: {
      floorCode: string;
      floorName?: string;
      /** Format: int32 */
      floorOrder: number;
      /**
       * @description 층의 캐노니컬 기준 높이(m). 역삼역은 B1=5 · B2=0 · B3=-5.
       *     클라이언트가 층 전환을 ΔY 로 판정하는 데 쓰므로 되도록 넣는다.
       * @example 0
       */
      nominalZ?: number;
    };
    ApiResponseFloorResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['FloorResponse'];
    };
    FacilityUpdateRequest: {
      facilityType: string;
      nameKo: string;
      nameEn?: string;
      mapX: number;
      mapY: number;
      /** Format: int64 */
      linkedNodeId?: number;
      isAccessible?: boolean;
      exitDetail?: components['schemas']['ExitDetailRequest'];
    };
    ApiResponseFacilityDetailResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['FacilityDetailResponse'];
    };
    ExitDetailResponse: {
      exitNumber?: string;
      outsideLatitude?: number;
      outsideLongitude?: number;
      descriptionKo?: string;
      descriptionEn?: string;
    };
    FacilityDetailResponse: {
      /** Format: int64 */
      facilityId?: number;
      /** Format: int64 */
      stationId?: number;
      /** Format: int64 */
      floorId?: number;
      facilityType?: string;
      nameKo?: string;
      nameEn?: string;
      mapX?: number;
      mapY?: number;
      /** Format: int64 */
      linkedNodeId?: number;
      isAccessible?: boolean;
      exitDetail?: components['schemas']['ExitDetailResponse'];
    };
    AccountUpdateRequest: {
      /** Format: int64 */
      stationId?: number;
      isActive?: boolean;
    };
    ApiResponseIceServersResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['IceServersResponse'];
    };
    IceServerResponse: {
      urls?: string[];
      username?: string;
      credential?: string;
    };
    IceServersResponse: {
      iceServers?: components['schemas']['IceServerResponse'][];
    };
    ApiResponseListFloorMapResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['FloorMapResponse'][];
    };
    FloorMapResponse: {
      /** Format: int64 */
      mapId?: number;
      /** Format: int64 */
      floorId?: number;
      floorCode?: string;
      mapType?: string;
      mapUrl?: string;
      /** Format: int32 */
      width?: number;
      /** Format: int32 */
      height?: number;
      scaleMPerPx?: number;
      originPxX?: number;
      originPxY?: number;
      frameAngleDeg?: number;
      version?: string;
      /**
       * @description 층의 캐노니컬 기준 높이(m). 층 바닥 기준이며 역삼역은 B1=5 · B2=0 · B3=-5.
       *     클라이언트가 WebXR 의 앵커 대비 ΔY 와 비교해 층 전환을 판정하는 데 쓴다.
       *     같은 층 안에서 높이가 갈리는 구간(역삼역 B0.5)은 이 값으로 구분할 수 없다.
       * @example 0
       */
      nominalZ?: number;
    };
    ApiResponseListFacilityResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['FacilityResponse'][];
    };
    FacilityResponse: {
      /** Format: int64 */
      facilityId?: number;
      /** Format: int64 */
      stationId?: number;
      /** Format: int64 */
      floorId?: number;
      facilityType?: string;
      nameKo?: string;
      nameEn?: string;
      mapX?: number;
      mapY?: number;
      /** Format: int64 */
      linkedNodeId?: number;
      isAccessible?: boolean;
    };
    ApiResponseListStationSearchResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['StationSearchResponse'][];
    };
    StationSearchResponse: {
      /** Format: int64 */
      stationId?: number;
      nameKo?: string;
      nameEn?: string;
      lineInfo?: string;
      provider?: string;
      externalId?: string;
      address?: string;
      latitude?: number;
      longitude?: number;
      serviceReady?: boolean;
    };
    ApiResponseListStationNearbyResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['StationNearbyResponse'][];
    };
    StationNearbyResponse: {
      /** Format: int64 */
      stationId?: number;
      nameKo?: string;
      nameEn?: string;
      lineInfo?: string;
      /** Format: int64 */
      distanceM?: number;
    };
    ApiResponseListRecommendedExitResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RecommendedExitResponse'][];
    };
    ExitLocation: {
      latitude?: number;
      longitude?: number;
    };
    RecommendedExitResponse: {
      /** Format: int64 */
      recommendationId?: number;
      /** Format: int64 */
      placeId?: number;
      /** Format: int64 */
      exitFacilityId?: number;
      exitNameKo?: string;
      exitNameEn?: string;
      /** Format: int32 */
      priority?: number;
      isPrimary?: boolean;
      reasonKo?: string;
      reasonEn?: string;
      /** Format: int32 */
      walkingTimeMin?: number;
      exitLocation?: components['schemas']['ExitLocation'];
    };
    ApiResponseListDestinationSearchResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['DestinationSearchResponse'][];
    };
    DestinationSearchResponse: {
      destinationType?: string;
      /** Format: int64 */
      destinationId?: number;
      nameKo?: string;
      nameEn?: string;
      category?: string;
      provider?: string;
      externalId?: string;
      address?: string;
      latitude?: number;
      longitude?: number;
      /** Format: int64 */
      distanceMeters?: number;
    };
    ApiResponseListConsultationListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationListResponse'][];
    };
    ConsultationListResponse: {
      consultationId?: string;
      /** Format: int64 */
      stationId?: number;
      /** @enum {string} */
      problemType?:
        | 'CANNOT_FIND_LOCATION'
        | 'WRONG_DIRECTION'
        | 'CANNOT_FIND_EXIT'
        | 'GATE_PROBLEM'
        | 'ELEVATOR_NEEDED'
        | 'CARD_PROBLEM'
        | 'OTHER';
      /** @enum {string} */
      status?:
        'WAITING' | 'ACCEPTED' | 'IN_PROGRESS' | 'ENDED' | 'CANCELED' | 'REJECTED' | 'FAILED';
      /**
       * Format: int64
       * @description 이 상담을 맡은 상담자. 수락 전이면 null.
       */
      counselorId?: number;
      /** Format: int64 */
      currentNodeId?: number;
      currentLocationLabel?: string;
      destinationType?: string;
      /** Format: int64 */
      destinationId?: number;
      destinationLabel?: string;
      /** Format: date-time */
      requestedAt?: string;
    };
    ApiResponseConsultationDetailResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationDetailResponse'];
    };
    ConsultationDetailResponse: {
      consultationId?: string;
      /** Format: int64 */
      stationId?: number;
      /** @enum {string} */
      problemType?:
        | 'CANNOT_FIND_LOCATION'
        | 'WRONG_DIRECTION'
        | 'CANNOT_FIND_EXIT'
        | 'GATE_PROBLEM'
        | 'ELEVATOR_NEEDED'
        | 'CARD_PROBLEM'
        | 'OTHER';
      /** @enum {string} */
      status?:
        'WAITING' | 'ACCEPTED' | 'IN_PROGRESS' | 'ENDED' | 'CANCELED' | 'REJECTED' | 'FAILED';
      currentLocationLabel?: string;
      destinationLabel?: string;
      videoConsent?: boolean;
      audioConsent?: boolean;
      /** Format: date-time */
      requestedAt?: string;
      signalingRoomId?: string;
      signalingAccessToken?: string;
    };
    ApiResponseConsultationResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationResponse'];
    };
    ConsultationResponse: {
      consultationId?: string;
      /** @enum {string} */
      status?:
        'WAITING' | 'ACCEPTED' | 'IN_PROGRESS' | 'ENDED' | 'CANCELED' | 'REJECTED' | 'FAILED';
      /** Format: int64 */
      counselorId?: number;
      signalingRoomId?: string;
      signalingAccessToken?: string;
    };
    SseEmitter: {
      /** Format: int64 */
      timeout?: number;
    };
    ApiResponseConsultationSummaryResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationSummaryResponse'];
    };
    ConsultationSummaryResponse: {
      consultationId?: string;
      /** @enum {string} */
      status?: 'PENDING' | 'COMPLETED' | 'FAILED';
      counselorName?: string;
      /** Format: date-time */
      endedAt?: string;
      /** @enum {string} */
      language?: 'ko' | 'en' | 'ja' | 'zh';
      summaryText?: string;
      startLocationLabel?: string;
      /** Format: int64 */
      guidedExitFacilityId?: number;
      guidedExitLabel?: string;
      routeType?: string;
      transcript?: components['schemas']['TranscriptSegmentResponse'][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      completedAt?: string;
    };
    TranscriptSegmentResponse: {
      /** Format: int32 */
      seq?: number;
      /** @enum {string} */
      speaker?: 'USER' | 'COUNSELOR';
      content?: string;
    };
    ApiResponseBoolean: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: boolean;
    };
    ApiResponseListStationResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['StationResponse'][];
    };
    StationResponse: {
      /** Format: int64 */
      stationId?: number;
      nameKo?: string;
      nameEn?: string;
      lineInfo?: string;
      latitude?: number;
      longitude?: number;
    };
    ApiResponseListFloorResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['FloorResponse'][];
    };
    ApiResponseListRouteNodeResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RouteNodeResponse'][];
    };
    ApiResponseListRouteEdgeResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RouteEdgeResponse'][];
    };
    ApiResponseListPlaceExitRecommendationResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['PlaceExitRecommendationResponse'][];
    };
    PlaceExitRecommendationResponse: {
      /** Format: int64 */
      recommendationId?: number;
      /** Format: int64 */
      placeId?: number;
      /** Format: int64 */
      exitFacilityId?: number;
      /** Format: int32 */
      priority?: number;
      reasonKo?: string;
      reasonEn?: string;
      /** Format: int32 */
      walkingTimeMin?: number;
      isPrimary?: boolean;
    };
    ApiResponseListNearbyPlaceResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['NearbyPlaceResponse'][];
    };
    AccountListResponse: {
      /** Format: int64 */
      accountId?: number;
      loginId?: string;
      name?: string;
      /** Format: int64 */
      stationId?: number;
      isActive?: boolean;
      /** @enum {string} */
      status?: 'AVAILABLE' | 'BUSY' | 'OFFLINE';
    };
    ApiResponseListAccountListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['AccountListResponse'][];
    };
    ApiResponseConsultationCancelResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ConsultationCancelResponse'];
    };
    ConsultationCancelResponse: {
      consultationId?: string;
      /** @enum {string} */
      status?:
        'WAITING' | 'ACCEPTED' | 'IN_PROGRESS' | 'ENDED' | 'CANCELED' | 'REJECTED' | 'FAILED';
    };
    ApiResponseVoid: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  localize: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          image: string;
          metadata: components['schemas']['LocalizationRequestMetadata'];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseLocalizationResponse'];
        };
      };
    };
  };
  createUserSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserSessionCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseUserSessionCreateResponse'];
        };
      };
    };
  };
  createRoute: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RouteCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRouteResponse'];
        };
      };
    };
  };
  getRouteOptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RouteOptionsRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListRouteOptionResponse'];
        };
      };
    };
  };
  checkArrival: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        facilityId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExitArrivalCheckRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseExitArrivalResponse'];
        };
      };
    };
  };
  createDirection: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExternalDirectionRequest'];
      };
    };
    responses: {
      /** @description 카카오맵 길찾기 URL 생성 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": true,
           *       "data": {
           *         "provider": "kakao",
           *         "appUrl": "kakaomap://route?sp=37.5665,126.9780&ep=37.4979,127.0276&by=foot",
           *         "webUrl": "https://map.kakao.com/link/by/walk/현재 위치,37.5665,126.9780/강남역,37.4979,127.0276"
           *       }
           *     }
           */
          '*/*': components['schemas']['ExternalDirectionResponse'];
        };
      };
      /** @description 지원하지 않는 provider/mode 또는 요청 값 검증 실패 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "BAD_REQUEST",
           *       "message": "지원하지 않는 외부 지도 제공자입니다."
           *     }
           */
          '*/*': unknown;
        };
      };
    };
  };
  findNearestExit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NearestExitRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseNearestExitResponse'];
        };
      };
    };
  };
  createConsultation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsultationCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseConsultationCreateResponse'];
        };
      };
    };
  };
  rejectConsultation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationSessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseConsultationRejectResponse'];
        };
      };
    };
  };
  endConsultation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationSessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsultationEndRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseConsultationEndResponse'];
        };
      };
    };
  };
  acceptConsultation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationSessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseConsultationAcceptResponse'];
        };
      };
    };
  };
  publishFallbackEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationRequestId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsultationFallbackEventRequest'];
      };
    };
    responses: {
      /** @description fallback 이벤트 발행 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": true,
           *       "data": null,
           *       "message": null
           *     }
           */
          '*/*': unknown;
        };
      };
      /** @description fallback 이벤트 타입 누락 또는 지원하지 않는 enum 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "INVALID_REQUEST",
           *       "message": "요청 형식이 올바르지 않습니다."
           *     }
           */
          '*/*': unknown;
        };
      };
    };
  };
  publishDataChannelEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationRequestId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsultationDataChannelEventRequest'];
      };
    };
    responses: {
      /** @description DataChannel fallback 이벤트 발행 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": true,
           *       "data": null,
           *       "message": null
           *     }
           */
          '*/*': unknown;
        };
      };
      /** @description DataChannel 이벤트 타입 누락 또는 지원하지 않는 enum 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "INVALID_REQUEST",
           *       "message": "요청 형식이 올바르지 않습니다."
           *     }
           */
          '*/*': unknown;
        };
      };
    };
  };
  submitTranscript: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsultationTranscriptRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseConsultationSummaryStatusResponse'];
        };
      };
    };
  };
  rate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsultationRatingRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseResponse'];
        };
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSignupResponse'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseLoginResponse'];
        };
      };
    };
  };
  getStations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListStationResponse'];
        };
      };
    };
  };
  createStation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StationCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseStationIdResponse'];
        };
      };
    };
  };
  getFloors: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListFloorResponse'];
        };
      };
    };
  };
  createFloor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stationId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FloorCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFloorIdResponse'];
        };
      };
    };
  };
  getNodes: {
    parameters: {
      query?: {
        stationId?: number;
        floorId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListRouteNodeResponse'];
        };
      };
    };
  };
  createNode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RouteNodeCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRouteNodeIdResponse'];
        };
      };
    };
  };
  getEdges: {
    parameters: {
      query?: {
        stationId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListRouteEdgeResponse'];
        };
      };
    };
  };
  createEdge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RouteEdgeCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRouteEdgeIdResponse'];
        };
      };
    };
  };
  getRecommendations: {
    parameters: {
      query?: {
        placeId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListPlaceExitRecommendationResponse'];
        };
      };
    };
  };
  createRecommendation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PlaceExitRecommendationCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePlaceExitRecommendationIdResponse'];
        };
      };
    };
  };
  getPlaces: {
    parameters: {
      query?: {
        stationId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListNearbyPlaceResponse'];
        };
      };
    };
  };
  createPlace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NearbyPlaceCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseNearbyPlaceIdResponse'];
        };
      };
    };
  };
  getMaps: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        floorId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListFloorMapResponse'];
        };
      };
    };
  };
  uploadMap: {
    parameters: {
      query: {
        request: components['schemas']['FloorMapUploadRequest'];
      };
      header?: never;
      path: {
        floorId: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /** Format: binary */
          mapFile?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFloorMapIdResponse'];
        };
      };
    };
  };
  getFacilities: {
    parameters: {
      query: {
        stationId: number;
        floorId?: number;
        facilityType?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListFacilityResponse'];
        };
      };
    };
  };
  createFacility: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FacilityCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFacilityIdResponse'];
        };
      };
    };
  };
  getUserSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userSessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseUserSessionResponse'];
        };
      };
    };
  };
  deleteUserSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userSessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseBoolean'];
        };
      };
    };
  };
  updateUserSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userSessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserSessionUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseUserSessionResponse'];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAccountDetailResponse'];
        };
      };
    };
  };
  updateMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CounselorSelfUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAccountDetailResponse'];
        };
      };
    };
  };
  getStation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseStationDetailResponse'];
        };
      };
    };
  };
  deleteStation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateStation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stationId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StationUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseStationDetailResponse'];
        };
      };
    };
  };
  getNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRouteNodeResponse'];
        };
      };
    };
  };
  deleteNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RouteNodeUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRouteNodeResponse'];
        };
      };
    };
  };
  getEdge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        edgeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRouteEdgeResponse'];
        };
      };
    };
  };
  deleteEdge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        edgeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateEdge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        edgeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RouteEdgeUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRouteEdgeResponse'];
        };
      };
    };
  };
  getPlace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        placeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseNearbyPlaceResponse'];
        };
      };
    };
  };
  deletePlace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        placeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updatePlace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        placeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NearbyPlaceUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseNearbyPlaceResponse'];
        };
      };
    };
  };
  deleteFloor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        floorId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateFloor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        floorId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FloorUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFloorResponse'];
        };
      };
    };
  };
  getFacility: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        facilityId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFacilityDetailResponse'];
        };
      };
    };
  };
  deleteFacility: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        facilityId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateFacility: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        facilityId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FacilityUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFacilityDetailResponse'];
        };
      };
    };
  };
  get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        accountId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAccountDetailResponse'];
        };
      };
    };
  };
  deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        accountId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        accountId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAccountDetailResponse'];
        };
      };
    };
  };
  getIceServers: {
    parameters: {
      query?: {
        token?: string;
      };
      header?: {
        Authorization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseIceServersResponse'];
        };
      };
    };
  };
  getStation_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseStationDetailResponse'];
        };
      };
    };
  };
  getStationMaps: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListFloorMapResponse'];
        };
      };
    };
  };
  getStationFacilities: {
    parameters: {
      query?: {
        floorId?: number;
        facilityType?: string;
        language?: string;
      };
      header?: never;
      path: {
        stationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListFacilityResponse'];
        };
      };
    };
  };
  searchStations: {
    parameters: {
      query?: {
        keyword?: string;
        language?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListStationSearchResponse'];
        };
      };
    };
  };
  getNearbyStations: {
    parameters: {
      query?: {
        latitude?: number;
        longitude?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListStationNearbyResponse'];
        };
      };
    };
  };
  getRecommendedExits: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        placeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListRecommendedExitResponse'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  getFacility_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        facilityId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFacilityDetailResponse'];
        };
      };
    };
  };
  search: {
    parameters: {
      query?: {
        stationId?: number;
        keyword?: string;
        language?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListDestinationSearchResponse'];
        };
      };
    };
  };
  getConsultations: {
    parameters: {
      query?: {
        status?:
          'WAITING' | 'ACCEPTED' | 'IN_PROGRESS' | 'ENDED' | 'CANCELED' | 'REJECTED' | 'FAILED';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListConsultationListResponse'];
        };
      };
    };
  };
  getConsultationDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationSessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseConsultationDetailResponse'];
        };
      };
    };
  };
  getConsultation: {
    parameters: {
      query: {
        userSessionId: string;
      };
      header?: never;
      path: {
        consultationSessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseConsultationResponse'];
        };
      };
    };
  };
  cancelConsultation: {
    parameters: {
      query: {
        userSessionId: string;
      };
      header?: never;
      path: {
        consultationSessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseConsultationCancelResponse'];
        };
      };
    };
  };
  subscribeWaitingEvents: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationRequestId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': components['schemas']['SseEmitter'];
        };
      };
    };
  };
  getSummary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consultationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseConsultationSummaryResponse'];
        };
      };
    };
  };
  checkLoginId: {
    parameters: {
      query: {
        loginId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseBoolean'];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        stationId?: number;
        isActive?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListAccountListResponse'];
        };
      };
    };
  };
  deleteRecommendation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recommendationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
}
